name: flutter_widgets
description: "Common & reusable widget's"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6

  # Screen Util
  flutter_screenutil: ^5.9.3

  # UI Helper Libraries
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue/Epilogue-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Epilogue/Epilogue-Light.ttf
          weight: 300
        - asset: assets/fonts/Epilogue/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/fonts/Epilogue/Epilogue-Medium.ttf
          weight: 500
        - asset: assets/fonts/Epilogue/Epilogue-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Epilogue/Epilogue-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueUltraLight.otf
          weight: 200
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueLight.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueRoman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueMedium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueBold.otf
          weight: 600
        - asset: assets/fonts/HelveticaNeue/HelveticaNeueHeavy.otf
          weight: 700